version: "3.8"

services:
  db:
    image: postgres:14.5
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=schedule
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: ./FastAPI_SQLAlchemy
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn FastAPI_SQLAlchemy.main:app --host 0.0.0.0 --port 8000'
    volumes:
      - .:/FastAPI_SQLAlchemy
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://admin:admin@db:5432/schedule
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`fastapi.localhost`)"

  traefik:
    image: traefik:v2.2
    ports:
      - "8008:80"
    volumes:
      - "./traefik.dev.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

#  parsers:
#    build: ./parsing
#    command: python3 run.py
#    environment:
#      - MEPHI_AUTH_URL=https://auth.mephi.ru/login?service=https%3A%2F%2Fhome.mephi.ru%2Fhome
#      - MEPHI_SCHEDULE_URL=https://home.mephi.ru/study_groups/
#      - HOME_MEPHI_URL=https://home.mephi.ru
#      - USERNAME=pia014
#      - PASSWORD==77artsuCcess

volumes:
  postgres_data: