"""add teacher translate

Revision ID: b1d64a30ed5e
Revises: f2c5b11ebba7
Create Date: 2023-09-16 11:50:08.836581

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b1d64a30ed5e"
down_revision = "f2c5b11ebba7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "teacher_translate",
        sa.Column("guid", sa.dialects.postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(length=255)),
        sa.Column("fullname", sa.String(length=255), nullable=True),
        sa.Column("lang", sa.String(length=2)),
        sa.Column("teacher_guid", sa.dialects.postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["teacher_guid"],
            ["teachers.guid"],
        ),
        sa.PrimaryKeyConstraint("guid"),
    )
    op.create_index(op.f("ix_teacher_translate_guid"), "teacher_translate", ["guid"])

    op.add_column("teachers", sa.Column("url", sa.String(length=2048), nullable=True))
    op.add_column("teachers", sa.Column("alt_url", sa.String(length=2048), nullable=True))
    op.execute(
        "UPDATE teacher_translate SET name = teachers.name, fullname = teachers.fullname, lang = teachers.lang, "
        "teacher_guid = teachers.guid FROM teachers"
    )

    op.drop_column("teachers", "name")
    op.drop_column("teachers", "fullname")
    op.drop_column("teachers", "lang")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("teachers", "url")
    op.drop_column("teachers", "alt_url")

    # Восстанавливаем столбцы name, fullname и lang в таблице teachers
    op.add_column("teachers", sa.Column("name", sa.String(length=255)))
    op.add_column("teachers", sa.Column("fullname", sa.String(length=255), nullable=True))
    op.add_column("teachers", sa.Column("lang", sa.String(length=2)))

    # Запускаем SQL-команду для копирования данных обратно из teacher_translate в teachers
    op.execute(
        "UPDATE teachers SET name = teacher_translate.name, fullname = teacher_translate.fullname, lang = teacher_translate.lang "
        "FROM teacher_translate WHERE teachers.guid = teacher_translate.teacher_guid"
    )

    op.drop_index(op.f("ix_teacher_translate_guid"), table_name="teacher_translate")
    op.drop_table("teacher_translate")
    # ### end Alembic commands ###
