from backend.api.database.models.academic import AcademicModel
from backend.api.database.models.corps import CorpsModel
from backend.api.database.models.group import GroupModel
from backend.api.database.models.lesson import LessonModel
from backend.api.database.models.lesson_translate import LessonTranslateModel
from backend.api.database.models.news import NewsModel
from backend.api.database.models.news_image import NewsImageModel
from backend.api.database.models.room import RoomModel
from backend.api.database.models.start_semester import StartSemesterModel
